### ISSUE TITLE
Identifying inline attachments with CID instead of name

### ISSUE THREAD

**Issue by meain** [xhit/go-simple-mail#101]
As of now, the library uses name field to identify inline attachments. As in, it expects the user to have the body in the format `<img src="cid:{name} ...>` and the attachment to be `mail.File{name: <name>}`.

This limitation is currently because the fact that we get the contentID based on the name [here](https://github.com/xhit/go-simple-mail/blob/e26e0d185c61b009312a591a8983e725bad9a130/message.go#L241) and also does [replaceCIDs](https://github.com/xhit/go-simple-mail/blob/e26e0d185c61b009312a591a8983e725bad9a130/message.go#L91) on the body.

There are a few drawbacks for this approach:
- One cannot attach different files with the same name inline
- With the currently implementation, I'm forced to use cids and names(the values of cids and names are out of my control) in `mail.File`, but Outlook does not like [certain names](https://support.microsoft.com/en-us/office/blocked-attachments-in-outlook-434752e1-02d3-4e90-9124-8b81e49a8519) (for example ones that ends with `.com`).

---

Proposal for a fix: We can optionally accept `CID` in `mail.File` and if a `CID` is provided, use that instead of name in the code locations I have mentioned earlier. I can send you a PR if you are interested.

**Comment by xhit** [comment]
Hi, please send a PR with the proposal
