### ISSUE TITLE
Custom encodig for email headers

### ISSUE THREAD

**Issue by meain** [xhit/go-simple-mail#102]
As of now, we always use `q` encoding for headers, but I'm assuming we could extend it to accommodate different encodings. We used to do this previously based on the value of `encoding` but that seems to have been removed in https://github.com/xhit/go-simple-mail/commit/7fdf6eac62d423846ccf212330d160192aec7caa possibly because we wanted different encoding for headers than messages.

My specific usecase is to disable encoding for headers because Outlook somehow is not liking when we do `q` encoding in the `.eml` files I try to import. Outlook seems to just send UTF-8 without any encoding as of now when I try to get `.eml` file from them. I'm assuming this(not encoding headers) is not valid according to the spec, but somehow Outlook expects it this way. Do let me know if you have additional information on what I could be doing wrong if you have previously worked with Outlook.

What are your thought on adding an additional field `headerEncoding` along with `encoding` in the `message` struct and using that to decide what encoding to perform ([ref](https://github.com/xhit/go-simple-mail/blob/e26e0d185c61b009312a591a8983e725bad9a130/message.go#L23))

**Comment by xhit** [comment]
I have not worked with Outlook, but I know Microsoft do some stuff that aren't standards.

The change seems simple, but adding `headerEncoding` requires support and additional encoding. If I read well, this needs to be `disableHeaderEncoding` to avoid apply it.

**Comment by meain** [comment]
I'm guessing according to [RFC6530](https://www.rfc-editor.org/rfc/rfc6530#section-7.1), UTF-8 is valid in headers without any additional encoding.

**Comment by meain** [comment]
> this needs to be `disableHeaderEncoding` to avoid apply it

That would be simpler approach. I was proposition a `headerEncoding` field in case we wanted to add a `base64` encoding at a later point.

**Comment by xhit** [comment]
Perfect, you are right, please send a PR with the `headerEncoding`, I maintain another package to parse the mail https://github.com/OfimaticSRL/parsemail, maybe we should merge some stuff from here to test some cases.
