### ISSUE TITLE
How to load template from *.eml?

### ISSUE THREAD

**Issue by crazyhulk** [xhit/go-simple-mail#110]
I  can not find a example to do it.

* HTML and text templates

Thx.

**Comment by xhit** [comment]
This package doesn't support direct EML parsing. But you can use  https://github.com/OfimaticSRL/parsemail and create the email to send it with go-simple-mail

**Comment by crazyhulk** [comment]
> This package doesn't support direct EML parsing. But you can use https://github.com/OfimaticSRL/parsemail and create the email to send it with go-simple-mail

Thx
