### ISSUE TITLE
Can't go get

### ISSUE THREAD

**Issue by ivanjaros** [xhit/go-simple-mail#12]
```
$ go get -u github.com/xhit/go-simple-mail/v2
cannot find package "github.com/xhit/go-simple-mail/v2" in any of:
        ...\github.com\xhit\go-simple-mail\v2 (from $GOROOT)
        ...\github.com\xhit\go-simple-mail\v2 (from $GOPATH)
```
I guess this is related to go modules?

**Comment by xhit** [comment]
Yes. First `go mod init` your project.

With a `go get github.com/xhit/go-simple-mail/v2` is enough.

**Comment by ivanjaros** [comment]
yeah, thought so...how do you develop without modules though? should one just go get without the v2 suffix?

**Comment by xhit** [comment]
Exactly. To develop without modules, copy your project in your `$GOPATH` directory and execute `go get github.com/xhit/go-simple-mail` without the v2 suffix.

**Comment by ivanjaros** [comment]
ok, i just wasn't sure if master matches the v2 branch.
