### ISSUE TITLE
Get encrypted function

### ISSUE THREAD

**Issue by hb0730** [xhit/go-simple-mail#19]
Please provide a function that can get the encryption, For example: SMTP = > encryption TLS
```go
const (
	// EncryptionNone uses no encryption when sending email
	EncryptionNone encryption = iota
	// EncryptionSSL sets encryption type to SSL when sending email
	EncryptionSSL
	// EncryptionTLS sets encryption type to TLS when sending email
	EncryptionTLS
)
```

**Comment by xhit** [comment]
Please see commit 31bc89d2dc664ba070410268245b51c2f0996d06 and let me know. Thanks.

**Comment by hb0730** [comment]
Yes, we can `mail.Encryption (1)` , Maybe we can get it based on specific parameters.example: 
```go 
var encryptionTypesMap = map[string]Encryption{
	"None":     EncryptionNone,
	"SSL/TLS":  EncryptionSSL,
	"STARTTLS": EncryptionTLS,
}

func GetEncryption(str string) Encryption {
	return encryptionTypesMap[str]
}
```
It's just an idea, and users can do it themselves

**Comment by xhit** [comment]
I prefer users make this type of functions. A package should returns an error when key not exists or have a default value for that keys.

An error need to be checked, and default values can give unintended behaviors.

Use enum can avoid have to analyze this package and focus in developer code in those cases.

Maybe I'm wrong. I'm here to learn, and add a new function is not a breaking change. Feel free to add a PR with your idea.

**Comment by weidongbcn** [comment]
with outlook I got Mail Error: SMTP Connection timed out.....

**Comment by xhit** [comment]
@weidongbcn please create another issue with encryption type and port used.

**Comment by xhit** [comment]
It's time to V3 so make all your ideas here: #53

**Comment by hb0730** [comment]
now I'll close issues
