### ISSUE TITLE
How to set up proxy for send email？

### ISSUE THREAD

**Issue by Morain-Miao** [xhit/go-simple-mail#24]
I had never seen it. If anyone finds it，where is it？Tell me,please.

**Comment by xhit** [comment]
Hi. Sorry, but it's a network/server issue and not code issue. Maybe you need to contact your network administrator to allow this outgoing connection.

**Comment by xhit** [comment]
Hi @Morain-Miao , now you can use a your custom connection https://github.com/xhit/go-simple-mail#send-with-custom-connection
