### ISSUE TITLE
cannot find package "github.com/xhit/go-simple-mail/v2" in any of:

### ISSUE THREAD

**Issue by Dontmindmes** [xhit/go-simple-mail#30]
D:\Test\Tets>go get github.com/xhit/go-simple-mail/v2
cannot find package "github.com/xhit/go-simple-mail/v2" in any of:
        c:\go\src\github.com\xhit\go-simple-mail\v2 (from $GOROOT)
        C:\Users\Code\go\src\github.com\xhit\go-simple-mail\v2 (from $GOPATH)

**Comment by xhit** [comment]
If your project directory isn't in `C:\Users\Code\go\src` then you need to init modules with `go mod init projectname` and then use the `go get github.com/xhit/go-simple-mail/v2` command.
