### ISSUE TITLE
Unify attachment handling API

### ISSUE THREAD

**Issue by jlinnosa** [xhit/go-simple-mail#33]
Currently we have the following function signatures for adding attachments to an Email struct:
```
func (email *Email) AddAttachment(file string, name ...string) *Email
func (email *Email) AddAttachmentBase64(b64File, name string) *Email
func (email *Email) AddAttachmentData(data []byte, filename, mimeType string) *Email
func (email *Email) AddInline(file string, name ...string) *Email
func (email *Email) AddInlineBase64(b64File, name, mimeType string) *Email
func (email *Email) AddInlineData(data []byte, filename, mimeType string) *Email
```
For some reason `AddAttachment` and `AddInline`  are variadic but only accept one name:
```
        if len(name) > 1 {
                email.Error = errors.New("Mail Error: Attach can only have a file and an optional name")
                return email
        }
```
Other functions take `name` as parameter and possibly also `mimeType`.

I propose we modify all these functions to accept `name` and `mimeType`. So the API would become:
```
func (email *Email) AddAttachment(file, name, mimeType string) *Email
func (email *Email) AddAttachmentBase64(b64Data, name, mimeType string) *Email
func (email *Email) AddAttachmentData(data []byte, name, mimeType string) *Email
func (email *Email) AddInline(file, name, mimeType string) *Email
func (email *Email) AddInlineBase64(b64Data, name, mimeType string) *Email
func (email *Email) AddInlineData(data []byte, name, mimeType string) *Email
```

edit. I changed argument name `b64File` -> `b64Data` so it is consistent with `file` and `data` arguments.

**Comment by jlinnosa** [comment]
I made a PR implementing these modifications.

**Comment by xhit** [comment]
Note: I don't speak english, sorry any mistake.

`AddAttachment` and `AddInline` actually receives `name` because it's possible call the function with the file path to attach only, and the name of file in attachment will be the name of attached file from function.

The name is only a new name that developer want to deliver.

For example, the developer can attach a file like this:
```go
AddAttachment("filepaht/aaa.txt")
```

And the developer can use a new name for the file

```go
AddAttachment("filepaht/aaa.txt","bbb.txt")
```

The attachment will be received like bbb.txt

And, the reason this is implemented that form is because a mandatory name will confuse some developers. Send mail with attachment is attach the file only, It's weird to see an implementation where name should change.

And about the mimetype, the package, with the name of file, can capture the mimeType. This not apply when attach a file from bytes and that's why these functions requires mimeType, but I think it's better remove the mimeType parameter and calculate the mimeType from name like other functions.

**Comment by jlinnosa** [comment]
One possibility would be to keep `AddAttachment` and `AddInline` as variadic, but accept mimeType as the second parameter for name. This doesn't change the function signature but offers all the functionality that the other functions provide.

**Comment by xhit** [comment]
I have another idea to unify all attachment.

All these methods:
```go
func (email *Email) AddAttachment(file string, name ...string) *Email
func (email *Email) AddAttachmentBase64(b64File, name string) *Email
func (email *Email) AddAttachmentData(data []byte, filename, mimeType string) *Email
func (email *Email) AddInline(file string, name ...string) *Email
func (email *Email) AddInlineBase64(b64File, name, mimeType string) *Email
func (email *Email) AddInlineData(data []byte, filename, mimeType string) *Email
```
Replace with only one and use a struct to define the attachment.

The struct:
```go
type File struct {
	Filepath string
	Name     string
	MimeType string
	B64File  string
	Data     []byte
	Inline   bool
}
```

The method to unify all:
```go
func (email *Email) Attach(file File) *Email
```

The commit cb2f4788003f13ffdf302a5203f8c4d7eb97e654 (non tested and WIP) is based on this idea. Feel free to test.

**Comment by xhit** [comment]
unify-attach branch is the branch to test this.

**Comment by hiendv** [comment]
Hi, @xhit 
Do you have any plan to support custom ContentID (cid)?

**Comment by xhit** [comment]
@jlinnosa I finished the Unify attachment api. Please see the unify-attach. There are some changes in my [last comment](https://github.com/xhit/go-simple-mail/issues/33#issuecomment-826495822)

The solution, if not problem with that, will be merged with a new version v3

**Comment by xhit** [comment]
@hiendv please fill another issue and I will respond on that.

**Comment by jlinnosa** [comment]
> @jlinnosa I finished the Unify attachment api. Please see the unify-attach. There are some changes in my [last comment](https://github.com/xhit/go-simple-mail/issues/33#issuecomment-826495822)
> 
> The solution, if not problem with that, will be merged with a new version v3

I'm ok with that. I looked over the changes in the PR and commented on some things.

**Comment by jlinnosa** [comment]
You could add a simple shim to implement the current API with this new function so there would be no need to bump the major version. This could be just a new feature. You could then deprecate and remove the old API when releasing v3 later.

**Comment by xhit** [comment]
Thanks, I will work on that maybe tomorrow.

**Comment by xhit** [comment]
Added in #35

Not a breaking change.

**Comment by jlinnosa** [comment]
Like I commented in the PR, please don't keep two separate implementations for the same functionality. That could be a major hindrance in the future.
