### ISSUE TITLE
Why is the NewClient function used to create a server?

### ISSUE THREAD

**Issue by serg-volodeev** [xhit/go-simple-mail#37]
The library is very good. I'm going to use it. But there are several questions. Why is the NewClient function used to create a server?
server := mail.NewSMTPClient()
Don't you think this is illogical? Or am I missing something?

**Comment by xhit** [comment]
The `server` variable can be renamed to `smtpClient` or whatever.

You create a client because it's possible to send multiple email messages to same client.
