### ISSUE TITLE
SMTP Connection timed out

### ISSUE THREAD

**Issue by enzofoucaud** [xhit/go-simple-mail#43]
Hello, I want to use the example to test program but I had a problem ..
I use the right parameter and good password and error is coming ^^

**Mail Error: SMTP Connection timed out**

My fault or any problem with localhost, tls or another one ?

Thanks a lot

![image](https://user-images.githubusercontent.com/15039645/125798396-7544c3e1-60c8-4ca1-bb7f-5930e5aa70ea.png)

![image](https://user-images.githubusercontent.com/15039645/125798079-43311964-5371-40cd-a0b0-198e64958273.png)

**Comment by xhit** [comment]
Hello. You are using encryption type STARTTLS, that server require SSL/TLS, so use encryption type `EncryptionSSLTLS`
