### ISSUE TITLE
Add methods to inspect body

### ISSUE THREAD

**Issue by Jaskerv** [xhit/go-simple-mail#44]
Hey,
Firstly I would like to say that this is an awesome package.

I would to request a set of methods to access the msg body for both html and alternative/text. Would this be possible?

**Comment by xhit** [comment]
Hey, you're welcome.

You can use the method `GetMessage` from `Email` struct to get a RFC822 formatted message.

If this is enough, it's ok, but if you want only the body, there isn't a method for that. I can achieve this in this week, PRs are welcome too

**Comment by Jaskerv** [comment]
Thanks for the quick response!

Currently I am inspecting the entire RFC822 message.

I'm just thinking it may be beneficial to have some getters to inspect message headers, body, and attachments for testing purposes.

**Comment by xhit** [comment]
It's time to V3 so make all your ideas here: #53

**Comment by xhit** [comment]
I have another package for that, see https://github.com/OfimaticSRL/parsemail
