### ISSUE TITLE
Can I get ID of mail when already send?

### ISSUE THREAD

**Issue by Warhead007** [xhit/go-simple-mail#47]
Hi, I want to know that have anyway to get mail ID when send by SMTP with this lib?

**Comment by xhit** [comment]
Hello, sorry for delay.

You can add the message ID before sent with `AddHeader` method. Example:

```go
email.AddHeader("Message-ID", "asbaag-agkjagkjfjno-asdkjl@mx.google.com")
```

But SMTP can modify the Message-ID header to assign its implementation. The good part is that the assigned MessageID by you can be in the mail so you don't need to catch it. Example if you use the Gmail SMTP server with above implementation:

```
Message-ID: <613a289c.1c69fb81.fc86c.8403@mx.google.com>
X-Google-Original-Message-ID: asbaag-agkjagkjfjno-asdkjl@mx.google.com
```

So, you have two solutions to solve this:

1. Assign the Message-ID before send the email and be good with that despite SMTP server use their own Message-ID
2. Use a IMAP server to catch the sent message of sender email, get the eml (after way maybe 10 seconds) and extract the Message-ID

Note that not all SMTP servers modify the Message-ID and not all that does that store the Message-ID assigned.

**Comment by Warhead007** [comment]
Hello xhit,

Thank for solution.

 I have a few questions :
1. It have a pattern of message-ID or I can random in my own way?
2. If can. Can you explain how to in Gmail SMTP and outlook SMTP for me?

thank you.

**Comment by xhit** [comment]
> It have a pattern of message-ID or I can random in my own way?

You can generate your own Message-ID randomly, an example: `random-uid@mail.example.com`

> If can. Can you explain how to in Gmail SMTP and outlook SMTP for me?

If you use Gmail or Outlook to send the email, the Message-ID is modified, but original Message-ID you set will be in the .eml, so you only need to catch that header, for example, in Gmail is `X-Google-Original-Message-ID`
