### ISSUE TITLE
MISSING_MIMEOLE Message has X-MSMail-Priority, but no X-MimeOLE

### ISSUE THREAD

**Issue by mantoze** [xhit/go-simple-mail#48]
I got this message in mailtrap.io "Spam check":
MISSING_MIMEOLE Message has X-MSMail-Priority, but no X-MimeOLE

<img width="742" alt="image" src="https://user-images.githubusercontent.com/4608590/133144707-0cee4982-e7b8-4b45-bad6-5f988053f9d7.png">

Is all good with this header?

>     SpamAssassin Rule: MISSING_MIMEOLE
> 
>     Standard description: Message has X-MSMail-Priority, but no X-MimeOLE
> 
>     Explanation
> 
>     The message is pretending to be generated by a Microsoft email program which uses the extension header X-MSMail-Priority, but is missing the extension header X-MimeOLE which is characteristic of Microsoft email.
> 
>     This suggests that the sender is using badly-written mailout software, rather than a genuine Microsoft email program.

**Comment by xhit** [comment]
If you use Outlook SMTP you can get that warning if you set the priority in email to send.

To avoid the warning, skip the priority. If you really need it, maybe adding header using `AddHeader` method can solve this problem, but I don't test it, I don't have a Microsoft Outlook email, so test and let me know

```go
email.AddHeader("X-MimeOLE", "Produced By My App v0.0.1")
```

Note, if works, only use it when you set low or high priority (If you always get the warning, use always if works).

**Comment by mantoze** [comment]
Yes, this header solved the problem.
Thank you.

**Comment by krystofklima** [comment]
I am trying to find same solving of problem. But where I can add 

email.AddHeader("X-MimeOLE", "Produced By My App v0.0.1")

I try to google how to add to Outlook this, but with no success.
is it writeable to registry or some next place ??

**Comment by xhit** [comment]
Hi @krystofklima.

You need to add this in this package if you use it as email sender.

In README you can find the doc how to use it.
