### ISSUE TITLE
 Error starting tcp server

### ISSUE THREAD

**Issue by V1def** [xhit/go-simple-mail#52]
Before that I used Linux, when I switched to Windows, I started to get an error when starting the program:
`Mail Error on dialing with encryption type STARTTLS: dial tcp 127.0.0.1:587: connectex: No connection could be made because the target machine actively refused it.`

**Comment by xhit** [comment]
You are trying to connect to 127.0.0.1 port 587, it's correct? Check if your SMTP test service is using that port with STARTTLS

**Comment by V1def** [comment]
> You are trying to connect to 127.0.0.1 port 587, it's correct? Check if your SMTP test service is using that port with STARTTLS

That's right, this code doesn't just work on Windows

**Comment by xhit** [comment]
exec in cmd `telnet 127.0.0.1 587`
