### ISSUE TITLE
Mail not reciving to Yahoo Accounts

### ISSUE THREAD

**Issue by vindevuser** [xhit/go-simple-mail#61]
Hi,
Mails not receiving to yahoo accounts.  Getting the error message 5.6.7(destination does not support SMTPUTF8 required for message delivery).  
Please give a soulution

**Comment by xhit** [comment]
I tried receiving to yahoo account and sending with a yahoo account too and not problem.

Can you provide a reproducible code? (avoid posting your yahoo account user and password)

**Comment by xhit** [comment]
Seems like a back configuration in the smtp server.

If the server supports the SMTPUTF8 extension, the package adds theSMTPUTF8 parameter.
