### ISSUE TITLE
Suggestion: make contentType enum public

### ISSUE THREAD

**Issue by yusufozturk** [xhit/go-simple-mail#62]
First of all, thank you for this great library.

If you can make mail.contentType enum public, we can hold plain text or html formats in enum instead of integer values.

Right now, we do:

```
// Check Content Type
if message.ContentType == 1 {
  // Set Body HTML String
  email.SetBody(mail.TextHTML, message.Body)
} else {
  // Set Body Plain String
  email.SetBody(mail.TextPlain, message.Body)
}
```

What I want to do, is setting message.ContentType as mail.ContentType, so I can use directly:

`email.SetBody(message.ContentType, message.Body)`

If you accept this suggestion, I can prepare a PR.

Thanks.

**Comment by xhit** [comment]
You are right, as a breaking change, you can make a PR where destination is V3.

Thanks

**Comment by yusufozturk** [comment]
@xhit opened the PR.

I made the changes with "Rename Symbol", so everything should be okay. Also did some basic tests like sending email, nothing is broken.

Thanks.

**Comment by xhit** [comment]
Done, thanks for the contribution!
