### ISSUE TITLE
text/calendar example

### ISSUE THREAD

**Issue by renodesper** [xhit/go-simple-mail#67]
After a bit of research, I found out that this project is capable of using a calendar in the body (https://github.com/xhit/go-simple-mail/pull/50).  Can someone give me an example of how to create the ics data that is acceptable to be used? I don't see any example on the PR that has been merged.

**Comment by xhit** [comment]
This package is only capable to add the calendar data, you need to use another package or custom way to add it.

Maybe https://github.com/arran4/golang-ical can help you.

**Comment by renodesper** [comment]
Thank you for the suggestion. I will check that out.
