### ISSUE TITLE
Discarding duplicate email address and setting error

### ISSUE THREAD

**Issue by aayush-sib** [xhit/go-simple-mail#70]
Hi
Thanks for creating this package, great work 👍 

I wanted to know if is there any specific reason why you are not adding a duplicate email address in recipients and setting error on email also?

```
email.recipients, err = addAddress(email.recipients, address.Address)
	if err != nil {
		email.Error = errors.New("Mail Error: " + err.Error() + "; Header: [" + header + "] Address: [" + addresses[i] + "]")
		return email
```

**Comment by xhit** [comment]
Hi

Internal requirement, maybe export a new variable to disable the check to be used for developers will provide what do you need without to do a breaking change.

**Comment by xhit** [comment]
Perfect! Please make a PR, I have time to review and make the release in Github

**Comment by mukulsib** [comment]
Hi @xhit 

I have raised [PR](https://github.com/xhit/go-simple-mail/pull/71) for above fix, please have a look.
