### ISSUE TITLE
No mail send

### ISSUE THREAD

**Issue by Forsskieken** [xhit/go-simple-mail#76]
Hi there,

Wireguard ui is using this program for sending mail...
I found that mail server settings are stored in  /etc/envirionment but it's not working

hostname=smtp.gmail.com
port=587
username=[this.emailadress@gmail.com](mailto:this.emailadress@gmail.com)
password=vlqsolltfknmwfcd #generated app passwd
authType=PLAIN
encryption=TLS
noTLSCeck=no
fromName="This Email"
from="[this.emailadress@gmail.com](mailto:this.emailadress@gmail.com)"

I have installed ssmtp and this can send mail..

**Comment by xhit** [comment]
Hi.

I don't know about configuration of Wireguard ui. Do you have the error returned? Maybe Wireguard ui is not setting the values, and, when you modify `/etc/envirionment` you need to restart the service and sometimes restart the server to apply changes

**Comment by Forsskieken** [comment]
I'm running the server in a LXC on Proxmox so restarting is not a problem...
This is the error:
Mail Error on dialing with encryption type STARTTLS: dial tcp 127.0.0.1:25: connect: connection refused
I can send mails with the extra installed ssmtp but of course Wireguard-Ui doesnùt use that

**Comment by xhit** [comment]
The error refers that wireguard ui is not setting the smtp configuration values you have, it's is using the default configuration mentioned here: https://github.com/ngoduykhanh/wireguard-ui#environment-variables, so  maybe you need to try this in your device: https://github.com/ngoduykhanh/wireguard-ui/issues/249

**Comment by xhit** [comment]
Closed due is not a problem of this package
