### ISSUE TITLE
Why is it not possible to use proxy? 

### ISSUE THREAD

**Issue by awiz911** [xhit/go-simple-mail#79]
I saw question and comment about proxy in closed issue. 

However it's not a network issue. 

With "net/smtp" and "golang.org/x/net/proxy" we can easily create smtpClient through proxy: 

```go
Dial, err := proxy.SOCKS5("tcp", "some-proxy-address", nil, proxy.Direct)
if err != nil {
	return nil, errors.Wrap(err, "Create SOCKS5")
}

dialer, err = Dial.Dial("tcp", "host-addr")
if err != nil {
	return nil, errors.Wrap(err, "Dial")
}

conf := &tls.Config{ServerName: "host-addr-without-port"}
tlsdialer := tls.Client(dialer, conf)

client, err := smtp.NewClient(tlsdialer, "host-addr")
if err != nil {
	panic(err)
}

auth := smtp.PlainAuth("", user, pass, "host-addr")
if err = client.Auth(auth); err != nil {
	panic(err)
}
```

And would be awesome if smth like this would be possible in this package. Cuz it's quite convient for sending mail.
Or if it's too much trouble, then why was smtpClient made not exportable in the first place. It has couple slight differences with net's smtp.Client type: there's a instead of auth and Text made exportable. 
If instead of creating separate type net's smtp.Client was used then we would have proxy as in code above.
Even if there's a different type, then methods to change connections would work too. 

Or add couple params to SMTPServer type for proxy and on connect if there are filled in use them for connection. 
So many ways to do it. Wander why it wasn't done in the first place. (

**Comment by awiz911** [comment]
Your english is fine. ) 

I might just do that actually. Will get payed for it too. ))) Without this package would have to pretty much make my own from scratch for project I'm working on. So this seems like a faster way to finish. )))

**Comment by xhit** [comment]
Hi @awiz911, now you can use a your custom connection https://github.com/xhit/go-simple-mail#send-with-custom-connection

Sorry for delay, thanks for the motivation 🚀

**Comment by awiz911** [comment]
@xhit I'm the one who should be sorry. ( Got caught up with work projects and code-contests and didn't find time to add solution myself. ( Thanks for great lib and great work.
