### ISSUE TITLE
Export priority type

### ISSUE THREAD

**Issue by nikoksr** [xhit/go-simple-mail#83]
Hi @xhit, 

thanks for your work on this! Just a quick question regarding the [priority](https://github.com/xhit/go-simple-mail/blob/457c8da4d84b1dc44cf64adb726f344129acc41d/email.go#L387) type. Is there any reason why it's not exported? It being an unexported type makes it kinda annoying to translate priorities between this and other packages.

If there's a specific reason, please let me know. If not, I got a PR basically ready!

Cheers

**Comment by xhit** [comment]
Not special reason, can be exported, if you need this ASAP please send a PR, I will take a look soon.

Cheers.

**Comment by nikoksr** [comment]
Thanks for the quick response! PR is up for you review.

We're utilizing your library in [Notify](https://github.com/nikoksr/notify), and making a move from [jordan-wright/email](https://github.com/jordan-wright/email) to your library and so far, it's been a blast.
