### ISSUE TITLE
Delivery receipt not working

### ISSUE THREAD

**Issue by Herz3h** [xhit/go-simple-mail#86]
I'm trying to get a delivery receipt using the header: `Return-Receipt-To` but I never receive any delivery notification.

I'm aware that most servers drop this header. But after digging it seems that the issue is that delivery status notification is not implemented in the library (https://datatracker.ietf.org/doc/html/rfc3464)

If server supports DSN extension, all it takes (as far I understood) is to add some parameters to the RCPT TO part. Example:

RCPT TO:<user@example.com> NOTIFY=SUCCESS,FAILURE ORCPT=rfc822;user@example.com

Would it be possible to add this ?

**Comment by xhit** [comment]
In master branch
