### ISSUE TITLE
Use Content-Type: text/x-amp-html

### ISSUE THREAD

**Issue by Smirnoff2019** [xhit/go-simple-mail#88]
Good day! And could you make it possible to send emails with Content-Type: text/x-amp-html. You removed this possibility by creating TextPlain and TextHTML constants as integers and using them in the SetBody and AddAlternative functions. 

P.S. At least add one more constant - TextAMP. This will not break the functionality of the package, it will only expand it.

**Comment by xhit** [comment]
In master
