### ISSUE TITLE
[Feature Req] Interface that accept To/CC with a single string

### ISSUE THREAD

**Issue by suntong** [xhit/go-simple-mail#93]
Please consider adding/allowing passing a single string to To/CC. Currently there is an extra check preventing it:

`Mail Error: mail: expected single address, got ",a2@gmail.com"; Header: [To] Address: [a1@gmail.com,a2@gmail.com]`

Reason being:

- It is perfectly fine to set the "`To:`" header to something like `"Alice <alice@example.com>, Bob <bob@example.com>, Eve <eve@example.com>"` _in plain email_, so such extra checking is too restrictive.
- I understand that there might be extra checking on the email address format checking, but since the basic text based unix email doesn't check it, such extra checking can be optional, IMHO. After all, if the user made mistakes in their to/cc email address, they will know eventually.
- And the most important thing is, to add more recipients, I have to _**change my code**_ to `AddTo` to do that, whereas the common sense/practice is to change data, not to change code, when covering different cases.

**Comment by xhit** [comment]
Hi.

I'm with you.

Currently I'm busy, but If you need this ASAP please send a PR, I will review it.

Thanks.

**Comment by suntong** [comment]
> Currently I'm busy, but If you need this ASAP please send a PR, I will review it.

Closing for the same reason as in #91.
