### ISSUE TITLE
Toggle to accept incomplete email address

### ISSUE THREAD

**Issue by meain** [xhit/go-simple-mail#95]
*This feature request might not fit the project's goals, but I wanted to check just in case you were open to adding it.*

We use this project to generate `.eml` files out of email data that we have in a different format. During this, it is possible that we might have "incomplete" emails in the `To` or other similar fields. This usually comes from draft emails where people abandon half way through and a few other reasons.

Currently when we try to encode these emails in to `.eml`, we end up getting an error usually complaining about a missing `@` as the email field might just contain a name or a Microsoft [`legacyExchangeDN`](https://www.enowsoftware.com/solutions-engine/exchange-center/bid/151745/the-attribute-the-myth-the-legacyexchangedn).

The proposal would be to add a toggle similar to `email.AllowDuplicateAddress` to accept incomplete email addresses. The expected change would be to optionally drop the code for [parsing](https://github.com/xhit/go-simple-mail/blob/abcd63ac2d0e87541de479cf261fe295146c7950/email.go#L339C4-L343) out email address and use the user provided string as is.

**Comment by xhit** [comment]
Hi, I can work with this today

**Comment by meain** [comment]
Awesome, I'll drop a PR to allow for incomplete emails.
