### ISSUE TITLE
Support attachments with empty data

### ISSUE THREAD

**Issue by pandeyabs** [xhit/go-simple-mail#96]
`Attach` returns an error [here](https://github.com/xhit/go-simple-mail/blob/abcd63ac2d0e87541de479cf261fe295146c7950/attach.go#L111) if an attachment file has no data. Is this by design? I don't see a reason why attachments can't be of size 0 bytes.

**Comment by meain** [comment]
```diff
diff --git a/attach.go b/attach.go
index 9aa48b6..809a8bb 100644
--- a/attach.go
+++ b/attach.go
@@ -108,7 +108,7 @@ func getAttachmentType(file *File) (attachType, error) {
 		return attachFile, nil
 	}
 
-	return 0, errors.New("empty attachment")
+	return attachData, nil
 }
 
 // attachB64 does the low level attaching of the files but decoding base64
```

FYI, this will be the only change we need. With this change it still generates valid .eml files (I tried a bunch of online viewers and it was able to parse them without issues). I can submit a PR if you want (and probably add a toggle as folks might also want to be warned about attaching a empty file).

**Comment by xhit** [comment]
A toggle `SupportEmptyAttachments` should be added to avoid a breaking change. Feel free to send a PR. Thanks.

**Comment by meain** [comment]
I've created a PR at https://github.com/xhit/go-simple-mail/pull/98 . I've named the toggle as `AllowEmptyAttachments` instead of `SupportEmptyAttachments` as other toggles also star with Allow.
